### ISSUE TITLE
Projectiles can be blocked without holding block, if they hit the saber box.

### ISSUE THREAD

**Issue by Boothand** [Boothand/SaberShenanigans#1]
Should only be when holding block.

**Comment by Boothand** [comment]
Removed reflecting so far.

**Comment by Boothand** [comment]
Was fixed in https://github.com/Boothand/SaberShenanigans/commit/279fe8db555832d3eba3d816e6b6bca9daab0ba6

**Comment by TriForceX** [comment]
What kind of projectiles this feature block?

**Comment by Boothand** [comment]
Stuff that can usually be blocked, blasters, bowcaster, some fragments of the shotgun. I think sniper actually, too. The repeater is an exception, it can be blocked at the saber box if it collides, but not sure if that one will make it to actual gameplay.

**Comment by TriForceX** [comment]
what about rockets or repeater alt fire? actually cant be blocked, maybe you can add an "auto-block" for that, so when u block, the player automatically do "force push" :tada:

**Comment by Boothand** [comment]
I don't know what to do with rockets and repeater in an actual guns & sabers gametype. I don't think such should be saber blocked, or involve force. Rockets are more about splash damage in my opinion, and if the respawn rate is high and the ammo low, I think they can stay as they are. Though the impact of rockets have already been reduced a bit: https://github.com/Boothand/SaberShenanigans/commit/279fe8db555832d3eba3d816e6b6bca9daab0ba6#diff-8f57da157b744d2cad9597ad1d75d33dL88

**Comment by TriForceX** [comment]
oh i see, in that case, u re right, is better to keep stay as they are.
